PUT http://localhost:3000/books HTTP/1.1
Content-Type: application/json

{
    "Title": "Mushoku Tensei - Isekai Ittara Honki Dasu",
    "Url": "https://manganelo.com/manga/mushoku_tensei_isekai_ittara_honki_dasu",
    "Image": "https://avt.mkklcdnv6temp.com/7/r/1-1583463967.jpg",
    "Folder": "Favorites"
}
###