POST http://localhost:8080/book/127 HTTP/1.1
Content-Type: application/json

  {
    "Id": 127,
    "Title": "Her Summon",
    "Sites": [
      {
        "SiteId": "dca5f6ed-e722-4087-ad49-20570c373f7d",
        "Url": "https://isekaiscan.com/manga/her-summon/",
        "Image": "https://isekaiscan.com/wp-content/uploads/2019/04/cover_250x350-1-193x278.jpg",
        "LastAttempted": "2021-12-16T11:18:17.063Z",
        "LastSuccessful": "2021-12-15T15:28:36.026Z"
      }
    ],
    "AltTitles": [],
    "Folder": "Finished",
    "LastUploaded": "2021-11-17T05:00:00.000Z"
  }
###